/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __RS_REFILLS_TYPE_DEFINITIONS_H__
#define __RS_REFILLS_TYPE_DEFINITIONS_H__

#define RS_REFILLS_REFILLS_PRODUCTFACING "rs_refills.refills.ProductFacing"

#endif /* __RS_REFILLS_TYPE_DEFINITIONS_H__ */
